### PR TITLE
retab and change linkedinfinder profile image location

### PR DESCRIPTION
**Pull request by brian13**
the retab makes it a bit busier than it really is... main change is element.find_all('div')[3]['class'] from [1]

### CODE REVIEW

**Comment by brian13** [comment]
yes i believe so.. i changed the ghost person + linkedin image element array to match what i suppose must be site changes over there.  person images aren't found otherwise

**Comment by Green-Wolf** [comment]
I just checked and the original code is still working for me. Not sure what the issue here is:

`$ python social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -m fast -li -s

[+] LinkedIn Login Page loaded successfully [+]
[+] LinkedIn Login Success [+]

LinkedIn Check 3/3 : Steve Jobs
Bill Gates
	LinkedIn: https://linkedin.com/in/williamhgates/

Linus Torvalds
	LinkedIn: https://linkedin.com/in/linustorvalds/

Steve Jobs
	LinkedIn: https://linkedin.com/in/steve-jobs-80b574141/

`

**Comment by brian13** [comment]
how strange, i only get results w/that array on 3 rather than 1

`python ./social_mapper.py --verbose -f imagefolder -i ./Input-Examples/imagefolder -m fast -li -s

[+] LinkedIn Login Page loaded successfully [+]
[+] LinkedIn Login Success [+]

LinkedIn Check 1/3 : Bill Gates
LinkedIn Check 2/3 : Linus Torvalds
LinkedIn Check 3/3 : Steve Jobs`

vs

`python ./social_mapper.py --verbose -f imagefolder -i ./Input-Examples/imagefolder -m fast -li -s

[+] LinkedIn Login Page loaded successfully [+]
[+] LinkedIn Login Success [+]

LinkedIn Check 1/3 : Bill Gates
        Match found: Bill Gates
        LinkedIn: https://linkedin.com/in/williamhgates/
LinkedIn Check 2/3 : Linus Torvalds
        Match found: Linus Torvalds
        LinkedIn: https://linkedin.com/in/linustorvalds/
LinkedIn Check 3/3 : Steve Jobs
        Match found: Steve Jobs
        LinkedIn: https://linkedin.com/in/steve-jobs-80b574141/`

(shrug)

**Comment by Green-Wolf** [comment]
Thanks for sharing though, i'll point others here if their LinkedIn search isn't working 👍

**Pull request closed without merging**
