### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
* __print()__ is a function in Python 3  #1
* Old style exceptions --> new style for Python 3

### CODE REVIEW

**Comment by Ewpratten** [comment]
I like that. also, if there is any multithreading, py3 uses a different lib if i remember correctly. (of not, this script should totally be multithreaded)

**Comment by cclauss** [comment]
You are probably thinking of https://docs.python.org/3/library/asyncio.html which Python 3 supports but Python 2 does not.

**Comment by Green-Wolf** [comment]
Hey thanks for the effort you've put into this, i've been doing some quick mergers tonight, but i'll test this soon. Looks great though.

**Comment by cclauss** [comment]
Bump on this one?

**Comment by Green-Wolf** [comment]
on my todo list, i've been advised changing to python3 can create some other errors with how strings are handled. So i want to do proper testing on this.

**Comment by cclauss** [comment]
These changes will work on both Python 2 and Python 3.

**Comment by Green-Wolf** [comment]
Hi @cclauss, I'm getting problems with urllib, i had a quick look and they don't seem compatible across versions:
$ python3 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -gp -s -m fast
Traceback (most recent call last):
  File "social_mapper.py", line 17, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

**Comment by Green-Wolf** [comment]
I've created a bunch of try except statements to handle the python 3 imports. However this is starting to seem like a large job with the string differences between python2 and python3. For example:
python3 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -gp -s -m fast
Traceback (most recent call last):
  File "social_mapper.py", line 1134, in <module>
    peoplelist = fill_googleplus(peoplelist)
  File "social_mapper.py", line 473, in fill_googleplus
    GooglePlusfinderObject.doLogin(google_username,google_password)
  File "/smtest/social_mapper-3369f366e1b1e541507efcbeeff11181f441ae8f/modules/googleplusfinder.py", line 35, in doLogin
    if(self.driver.title.encode('utf8','replace').startswith("Discover")):
**TypeError: startswith first arg must be bytes or a tuple of bytes, not str**

**Comment by cclauss** [comment]
I would try to replace urllib with requests wherever you can.  It works the same on both Python 2 and Python 3 and it automatically deals with many of the special cases that urllib makes you handle manually.

**Comment by cclauss** [comment]
request.get().text gives you Unicode

request.get().content gives you bytes

request.get().json() gives you json

**Comment by cclauss** [comment]
The error message you got is strange given https://docs.python.org/3/library/stdtypes.html#str.startswith

**Comment by cclauss** [comment]
Let's think about this PR a bit differently.  It is not an attempt to _complete_ the port to Python 3.  It is merely an attempt to modernize the Python 2 code to be _syntax compatible_ with both Python 2 and Python 3.  So if the code in this PR works properly on Python 2 then please consider merging it.

Landing the `from __future__ import print_function` lines in the codebase will prevent the addition of __print__ statements that are not __print()__ function and that alone will simplify the porting effort.

**Comment by Green-Wolf** [comment]
Ah i see thanks @cclauss, I was thinking of it as full port/compatibility. I'll merge in your changes as they are perfectly compatible with python 2. Thanks very much for the help!

**Comment by Green-Wolf** [comment]
Added @cclauss to list of contributors in the acknowledgements section of the project. Let me know if you don't wish to be included. Thank you again for your time and effort. 🥇

**Pull request merged**
